task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
multi_gpu: false
num_threads: 4
solver_type: 1
test: false
checkpoint: ''
evaluation: false
headless: false
enable_livestream: true
mt_timeout: 300
enable_recording: false
recording_interval: 2000
recording_length: 100
recording_fps: 30
recording_dir: ''
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: omniisaacgymenvs
kit_app: ''
warp: false
task:
  name: FactoryTaskAllocationMiC
  physics_engine: ${..physics_engine}
  sim:
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    dt: 0.00833333333
    gravity_mag: 9.81
    disable_gravity: false
    add_ground_plane: true
    add_distant_light: false
    use_fabric: true
    enable_scene_query_support: true
    disable_contact_processing: false
    default_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 16
      solver_velocity_iteration_count: 0
      contact_offset: 0.005
      rest_offset: 0.0
      worker_thread_count: ${....num_threads}
      solver_type: ${....solver_type}
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.01
      friction_correlation_distance: 0.00625
      max_depenetration_velocity: 5.0
      enable_sleeping: true
      enable_stabilization: true
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 33554432
      gpu_found_lost_pairs_capacity: 8192
      gpu_found_lost_aggregate_pairs_capacity: 262144
      gpu_total_aggregate_pairs_capacity: 1048576
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 33554432
      gpu_temp_buffer_capacity: 16777216
      gpu_max_num_partitions: 8
    franka:
      override_usd_defaults: false
      enable_self_collisions: true
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 16
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: 1000.0
      max_depenetration_velocity: 5.0
      contact_offset: 0.005
      rest_offset: 0.0
    nut:
      solver_position_iteration_count: 16
      solver_velocity_iteration_count: 0
    bolt:
      solver_position_iteration_count: 16
      solver_velocity_iteration_count: 0
  env:
    controlFrequencyInv: 2
    numEnvs: ${resolve_default:1,${...num_envs}}
    numObservations: 20
    numActions: 10
    dimActions: 1
    close_and_lift: true
    num_gripper_move_sim_steps: 40
    num_gripper_close_sim_steps: 40
    num_gripper_lift_sim_steps: 40
  randomize:
    franka_arm_initial_dof_pos:
    - 0.3413
    - -0.8011
    - -0.067
    - -1.8299
    - 0.0266
    - 1.0185
    - 1.0927
    fingertip_midpoint_pos_initial:
    - 0.0
    - -0.2
    - 0.2
    fingertip_midpoint_pos_noise:
    - 0.2
    - 0.2
    - 0.1
    fingertip_midpoint_rot_initial:
    - 3.1416
    - 0
    - 3.1416
    fingertip_midpoint_rot_noise:
    - 0.3
    - 0.3
    - 1
    nut_pos_xy_initial:
    - 0.0
    - -0.3
    nut_pos_xy_noise:
    - 0.1
    - 0.1
    bolt_pos_xy_initial:
    - 0.0
    - 0.0
    bolt_pos_xy_noise:
    - 0.1
    - 0.1
  rl:
    pos_action_scale:
    - 0.1
    - 0.1
    - 0.1
    rot_action_scale:
    - 0.1
    - 0.1
    - 0.1
    force_action_scale:
    - 1.0
    - 1.0
    - 1.0
    torque_action_scale:
    - 1.0
    - 1.0
    - 1.0
    clamp_rot: true
    clamp_rot_thresh: 1.0e-06
    num_keypoints: 4
    keypoint_scale: 0.5
    keypoint_reward_scale: 1.0
    action_penalty_scale: 0.0
    max_episode_length: 10240
    success_bonus: 0.0
  ctrl:
    ctrl_type: joint_space_id
    all:
      jacobian_type: geometric
      gripper_prop_gains:
      - 100
      - 100
      gripper_deriv_gains:
      - 2
      - 2
    gym_default:
      ik_method: dls
      joint_prop_gains:
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
      joint_deriv_gains:
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      gripper_prop_gains:
      - 500
      - 500
      gripper_deriv_gains:
      - 20
      - 20
    joint_space_ik:
      ik_method: dls
      joint_prop_gains:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      joint_deriv_gains:
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    joint_space_id:
      ik_method: dls
      joint_prop_gains:
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
      joint_deriv_gains:
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
    task_space_impedance:
      motion_ctrl_axes:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      task_prop_gains:
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
      task_deriv_gains:
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
    operational_space_motion:
      motion_ctrl_axes:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      task_prop_gains:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      task_deriv_gains:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
    open_loop_force:
      force_ctrl_axes:
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0
    closed_loop_force:
      force_ctrl_axes:
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0
      wrench_prop_gains:
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    hybrid_force_motion:
      motion_ctrl_axes:
      - 1
      - 1
      - 0
      - 1
      - 1
      - 1
      task_prop_gains:
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
      task_deriv_gains:
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      force_ctrl_axes:
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0
      wrench_prop_gains:
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
train:
  params:
    seed: ${...seed}
    algo:
      name: rainbow
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:FactoryTaskAllocationMiC,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      env_name: rlgpu
      multi_gpu: false
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0001
      lr_schedule: fixed
      schedule_type: standard
      kl_threshold: 0.016
      score_to_win: 20000
      max_epochs: ${resolve_default:200,${....max_iterations}}
      save_best_after: 50
      save_frequency: 100
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: false
      e_clip: 0.2
      horizon_length: 1024
      minibatch_size: 4
      mini_epochs: 8
      critic_coef: 2
      clip_value: true
      seq_length: 4
      bounds_loss_coef: 0.0001
      env_rule_based_exploration: true
