params:
  seed: ${...seed}
  algo:
    name: rainbow
  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  config:
    name: ${resolve_default:FactoryTaskAllocationMiC,${....experiment}}
    wandb_activate: ${....wandb_activate}
    full_experiment_name: ${.name}
    device: ${....rl_device}
    device_name: ${....rl_device}
    env_name: rlgpu
    multi_gpu: False
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: fixed
    schedule_type: standard
    kl_threshold: 0.016
    score_to_win: 20000
    max_epochs: ${resolve_default:200,${....max_iterations}}
    save_best_after: 50
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 2500
    minibatch_size: 4
    mini_epochs: 8
    critic_coef: 2
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0001
    env_rule_based_exploration: True
